Insert into Provincias values('CAPITAL')
Insert into Provincias values('BUENOS AIRES')
Insert into Provincias values('CATAMARCA')
Insert into Provincias values('CORDOBA')
Insert into Provincias values('CORRIENTES')
Insert into Provincias values('CHACO')
Insert into Provincias values('CHUBUT')
Insert into Provincias values('ENTRE RIOS')
Insert into Provincias values('FORMOSA')
Insert into Provincias values('JUJUY')
Insert into Provincias values('LA PAMPA')
Insert into Provincias values('LA RIOJA')
Insert into Provincias values('MENDOZA')
Insert into Provincias values('MISIONES')
Insert into Provincias values('NEUQUEN')
Insert into Provincias values('RIO NEGRO')
Insert into Provincias values('SALTA')
Insert into Provincias values('SAN JUAN')
Insert into Provincias values('SAN LUIS')
Insert into Provincias values('SANTA CRUZ')
Insert into Provincias values('SANTA FE')
Insert into Provincias values('SANTIAGO DEL ESTERO')
Insert into Provincias values('TIERRA DEL FUEGO')
Insert into Provincias values('TUCUMAN')
